SELECT WKT_PAYMENT::DATE WKT_PAYMENT,
COUNT(DISTINCT VA_NUMBER)jumlah_VA_NUMBER,
COUNT(DISTINCT NO_BARCODE)jumlah_NO_BARCODE,
SUM(BSU_BLB )BSU_BLB,
SUM(BSU_BEASIMPAN )BSU_BEASIMPAN,
SUM(BSU_BILLING )BSU_BILLING,
SUM(BSU_HANDLING )BSU_HANDLING,
SUM(BSU_PAYMENT )BSU_PAYMENT,
SUM(PPN_BEASIMPAN )PPN_BEASIMPAN,
SUM(PPN_BLB)PPN_BLB,
SUM(PPN_HANDLING )PPN_HANDLING
FROM ln_incoming_va
WHERE wkt_payment IS NOT NULL
GROUP BY 1